### ISSUE TITLE
메인 페이지, 로그인 회원가입 뷰 만들기

### ISSUE THREAD

**Issue by aaej0413** [aaej0413/give-and-take#1]
* [x] 로그인 뷰 만들기
* [x] 회원가입 뷰 만들기
* [x] 메인페이지 뷰 만들기

**Comment by mungmungtei** [comment]
메인페이지, 로그인, 회원가입 뷰 만듦
html, css 만 사용하여 만든 뷰라서 추후에 타임리프 문법으로 일부 적용시켜야 함

**Comment by mungmungtei** [comment]
머지 완료
